spring:
  profiles: dev

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      root: DEBUG
