spring:
  profiles: test

  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  logging:
    level:
      root: WARN
