spring:
  profiles: prod

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  logging:
    level:
      root: INFO
